import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Hello UI</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main className='c-layout-grid c-sidebar-layout-container'>
				<h1>Hola mundo</h1>
				<h2>Prueba</h2>
			</main>
		</>
	);
}
